name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 Voici le fichier github_actions du TP de TESTS UNITAIRES"
      - uses: actions/checkout@v2
      - run: pip install joblib
      - run: pip install sklearn
      - run: pip install streamlit
      - run: pip install -U Jinja2
      - run: pip install pytest
      - run: npm install -g n
      - run: npm install cypress
      - run: pytest test.py
      - run: streamlit run model_dashboard.py &
      - run: cypress run